---
title: "R Notebook"
output: html_notebook
---

Script: print_all_motifs.R
Author: Ignatius Pang 
Date: 13-7-2016
Description: I want to convert each of the 15 triplet motifs into an edge list, so I can show them in Cytoscape and make pictures.

```{r}
library(RCy3)
library(dplyr)

# source_directory_common <- "/home/ignatius/PostDoc/2016/Triplet_Motifs/Source/Common/"
source_directory_common <- "/home/ignatius/Documents/Postdoc/2016/Triplet_Motifs/Source/Common/"


source( file.path ( source_directory_common, 'draw_triplet_motif_network_helper.R') ) 

```


## Enumerate of all types of triplet motifs.
```{r}
types_of_edges <-  c( 'kd', 'ku', 'p', 'td', 'tu' ) 

triplet_motifs <- data.frame( type_ac = rep( sort(types_of_edges), 5) , type_bc= sort(rep( types_of_edges, 5) ), stringsAsFactors =FALSE ) %>%
					dplyr::filter( type_ac >= type_bc)


# Sort the motif types
triplet_motifs <- triplet_motifs %>% arrange( type_ac, type_bc)

# Determine the number of columns and rows for the edge list.
num_rows <- length(triplet_motifs[,1]) * 3 # Number of edges among all triplet motifs
num_cols <- 3 ## Total number of columns

## Initiate the matrix for the edge list
triplet_motif_figure <- data.frame(matrix(ncol = num_cols, nrow = num_rows))
colnames( triplet_motif_figure) <- c("gene_a", "gene_b", "interaction_type")


## Generate node names for the 15 types of triplet motifs. 
## On name for each node of the 15 types of motifs. Append letter 'a' to make sure there is enough motifs.
nodes_names <- c( letters, paste ( "a", letters, sep=""))
current_row <- 1

### Loop through the list of all possible motifs to create the edge list.
for ( i in 1:length(triplet_motifs[,1]) ) {
	
	current_letter_pointer <- (i-1)*3 + 1
	
	# a -- b edge of the triplet motif
	triplet_motif_figure[current_row, 1] <- nodes_names[current_letter_pointer]
	triplet_motif_figure[current_row, 2] <- nodes_names[current_letter_pointer + 1]
	triplet_motif_figure[current_row, 3] <- "gi"
	
	current_row <- current_row + 1
	 
	# a --- c edge of the triplet motif
	triplet_motif_figure[current_row, 1] <- nodes_names[current_letter_pointer]
	triplet_motif_figure[current_row, 2] <- nodes_names[current_letter_pointer + 2]
	triplet_motif_figure[current_row, 3] <- as.character ( triplet_motifs[i,1] )
	
	current_row <- current_row + 1
	
	
	# b --- c edge of the triplet motif
	triplet_motif_figure[current_row, 1] <- nodes_names[current_letter_pointer + 1]
	triplet_motif_figure[current_row, 2] <- nodes_names[current_letter_pointer + 2]
	triplet_motif_figure[current_row, 3] <- as.character( triplet_motifs[i,2]) 
	
	current_row <- current_row + 1
	
	
}


### Use R Cytoscape to add the edges into the Cytoscape network

## Add the list of nodes
list_of_nodes <- unique( c(triplet_motif_figure[,1], triplet_motif_figure[,2]))

graph_nel_object <- new ('graphNEL', edgemode='undirected')

graph_nel_object <- graph::addNode( as.character( list_of_nodes) , graph_nel_object)

#######################################################################################################################

## Add node attributes

# protein A and B
protein_A_attributes <- sapply ( triplet_motif_figure[,3], function(x) { ifelse( x == 'kd', 'kinase', NA ) } ) 

protein_A_attributes <- sapply ( names(protein_A_attributes), function(x) { ifelse( x == 'td', 'transcription factor', 
																							  	protein_A_attributes[x] ) } ) 

names( protein_A_attributes) <- triplet_motif_figure[,1]
	
# protein C

protein_C_attributes <- sapply ( triplet_motif_figure[,3], function(x) { ifelse( x == 'ku', 'kinase', NA ) } ) 

protein_C_attributes <- sapply ( names(protein_C_attributes), function(x) { ifelse( x == 'tu', 'transcription factor', 
																					protein_C_attributes[x] ) } ) 

names( protein_C_attributes) <- triplet_motif_figure[,2]



protein_A_attributes <- protein_A_attributes[is.na(protein_A_attributes)==FALSE]

protein_C_attributes <- protein_C_attributes[is.na(protein_C_attributes)==FALSE]


################################### 
# Add Node attributes, whether it is a kinase or a transcription factor.

cw <- CytoscapeWindow ( 'All triplet motifs ', graph=graph_nel_object, overwrite=TRUE)
graph_nel_object <- cw@graph

graph_nel_object <- initNodeAttribute( graph=graph_nel_object, attribute.name='is_kinase', attribute.type='integer', default.value=0)
nodeData (graph_nel_object, unique(names(protein_A_attributes[protein_A_attributes=='kinase'])), 'is_kinase'   ) <- rep( 1, length(unique(names(protein_A_attributes[protein_A_attributes=='kinase'] ))) )
nodeData (graph_nel_object, unique(names(protein_C_attributes[protein_C_attributes=='kinase'])), 'is_kinase'   ) <- rep( 1, length(unique(names(protein_C_attributes[protein_C_attributes=='kinase'] ))) )
																														 


graph_nel_object <- initNodeAttribute( graph=graph_nel_object, attribute.name='is_tf', attribute.type='integer', default.value=0)
nodeData (graph_nel_object, unique(names(protein_A_attributes[protein_A_attributes=='transcription factor'])), 'is_tf'   ) <- rep( 1, length(unique(names(protein_A_attributes[protein_A_attributes=='transcription factor'] ))) )
nodeData (graph_nel_object, unique(names(protein_C_attributes[protein_C_attributes=='transcription factor'])), 'is_tf'   ) <- rep( 1, length(unique(names(protein_C_attributes[protein_C_attributes=='transcription factor'] ))) )


#######################################################################################################################

## Add edges

graph_nel_object <- initEdgeAttribute (graph_nel_object, "edgeType", "char", "gi")

gene_a <- as.character( as.vector(t(triplet_motif_figure[, c("gene_a")])) )
gene_b <- as.character( as.vector(t(triplet_motif_figure[, c("gene_b")])) )

graph_nel_object <- graph::addEdge(gene_a, gene_b, graph_nel_object) 

edge_type_attributes <- as.character( as.vector(t(triplet_motif_figure[, c("interaction_type")])) )

edgeData( graph_nel_object, gene_a, gene_b, "edgeType") <- edge_type_attributes

#######################################################################################################################

### Create the network visualization

cw <- setGraph(cw, graph_nel_object)

displayGraph(cw)

layoutNetwork(cw, layout.name = "force-directed")

#######################################################################################################################

### Add Network Style

triplet_motif_network_display_style_all_triple_motifs <- function(cw) {

	setEdgeColorRule(cw, 'edgeType',
					 control.points=c( 'ku', 'kd', 'gi', 'tu', 'td', 'p'), 
					 colors=c('#0000ff', '#0000ff', '#00ff00', '#ff0000', '#ff0000', '#000000'), 
					 mode='lookup', default.color='#808080')
	
	setEdgeSourceArrowRule(cw, 'edgeType',
						   attribute.values=c( 'ku', 'kd', 'gi', 'tu', 'td', 'p'), 
						   arrows=c('ARROW', 'NONE', 'NONE', 'ARROW', 'NONE', 'NONE'), 
						   default='NONE')
	
	setEdgeTargetArrowRule(cw, 'edgeType',
						   attribute.values=c( 'ku', 'kd', 'gi', 'tu', 'td', 'p'), 
						   arrows=c('NONE', 'ARROW', 'NONE', 'NONE', 'ARROW', 'NONE'),  
						   default='NONE')
	
	setEdgeSourceArrowColorRule(cw, 'edgeType',
								control.points=c( 'ku', 'kd', 'gi', 'tu', 'td', 'p'), 
								colors=c('#0000ff', '#0000ff', '#00ff00', '#ff0000', '#ff0000', '#000000'), 
								mode='lookup', default.color='#808080')
	
	setEdgeTargetArrowColorRule(cw, 'edgeType',
								control.points=c( 'ku', 'kd', 'gi', 'tu', 'td', 'p'), 
								colors=c('#0000ff', '#0000ff', '#00ff00', '#ff0000', '#ff0000', '#000000'),  
								mode='lookup', default.color='#808080')
}

triplet_motif_network_display_style_all_triple_motifs (cw) 

#######################################################################################################################
```


```{r}
#########################################################################################################  
### Draw the 6 different edge types (gi, p, tu, td, ku, kd), for use as a legend.
#########################################################################################################  


## Draw these in another Cytoscape window.
graph_nel_object <- new ('graphNEL', edgemode='undirected')

cw <- CytoscapeWindow ( 'All types of edges', graph=graph_nel_object, overwrite=TRUE)
graph_nel_object <- cw@graph   # Once you created the cw object, it is important to get the graphNEL object back, otherwise the pointer is lost

### Add Nodes
graph_nel_object <- graph::addNode( c( 'BA', 'BB', 'BC', "BD", "BE", "BF", "BG", "BH") , graph_nel_object)

## Add edges
graph_nel_object <- initEdgeAttribute (graph_nel_object, "edgeType", "char", "gi")

gene_a <- c('BA', 'BC', 'BE', 'BG')
gene_b <- c('BB', 'BD', 'BF', 'BH')

graph_nel_object <- graph::addEdge(gene_a, gene_b, graph_nel_object) 

## Add edge attributes
edge_type_attributes <- c("p", 'td', 'kd', 'gi')

edgeData( graph_nel_object, gene_a, gene_b, "edgeType") <- edge_type_attributes

edgeData( graph_nel_object, "BA", "BB", "edgeType") <- 'p'
edgeData( graph_nel_object, "BC", "BD", "edgeType") <- 'td'
edgeData( graph_nel_object, "BE", "BF", "edgeType") <- 'kd'
edgeData( graph_nel_object, "BG", "BH", "edgeType") <- 'gi'

## Display the edge types
cw <- setGraph(cw, graph_nel_object)

displayGraph(cw)

layoutNetwork(cw, layout.name = "force-directed")

triplet_motif_network_display_style_all_triple_motifs (cw) 

################################### 

```



```{r}

### Converting igraph to graphNEL does not work, probably need to e-mail igraph author, RCy3 author to find out why

# g3 <- make_star(10, mode="in")
# V(g3)$name <- letters[1:10]
# GNEL2 <- as_graphnel(g3)
# 
# 
# cw <- RCy3::setGraph(cw, GNEL2)
# 
# 
# RCy3::displayGraph(cw)
# 
# RCy3::layoutNetwork(cw, layout.name = "force-directed")
# plot(GNEL2)

```
